package com.he.rating.dao;

import com.he.rating.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    ShopModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Mon Mar 24 19:15:29 EDT 2025
     */
    int updateByPrimaryKey(ShopModel record);

    List<ShopModel> selectAll();

    Integer countAllShop();

    List<ShopModel> recommend(
            @Param("longitude") BigDecimal longitude,
            @Param("latitude") BigDecimal latitude
    );

    List<ShopModel> search(
            @Param("longitude") BigDecimal longitude,
            @Param("latitude") BigDecimal latitude,
            @Param("keyword") String keyword,
            @Param("orderby") Integer orderby,
            @Param("categoryId") Integer categoryId,
            @Param("tags") String tags
    );

    List<Map<String, Object>> searchGroupByTags(
            @Param("keyword")String keyword,
            @Param("categoryId")Integer categoryId,
            @Param("tags")String tags);
}