package com.he.rating.dao;

import com.he.rating.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    UserModel selectByPrimaryKey(Integer id);

    UserModel selectByTelephoneAndPassword(
            @Param("telephone") String telephone,
            @Param("password") String password
    );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Mar 21 21:56:46 EDT 2025
     */
    int updateByPrimaryKey(UserModel record);


    Integer countAllUser();
}