version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rating
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: spring_password
    command:
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog_row_image=FULL
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: