spring:
  web:
    resources:
      add-mappings: false # ???????????
  application:
    name: rating
  profiles:
    active: dev # select dev or prod yaml files

  datasource: # ????????
    type: com.zaxxer.hikari.HikariDataSource      # ???????????????????????druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB ?????????
    url: jdbc:mysql://127.0.0.1:3306/rating?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: spring_user
    password: spring_password
    hikari:
      pool-name: DataSourceHikariCP           # ??????
      connection-timeout: 30000               # ??????????????????????????????????????SQLException
      minimum-idle: 5                         # ?????
      maximum-pool-size: 20                   # ?????
      auto-commit: true                       # ????
      idle-timeout: 600000                    # ??????????????????????retired?
      max-lifetime: 18000000                  # ???????????????????????retired?
      connection-test-query: SELECT 1

# MyBatisPlus ???
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
  mapper-locations: classpath*:/mapping/*.xml